module.exports = [
  {"category":"Gaming","difficulty":"Easy","question":"Who is Mario's brother?","choices":["Wario","Luigi","Toad","Yoshi"],"correctIndex":1},
  {"category":"Gaming","difficulty":"Easy","question":"Which blue hedgehog is SEGA's mascot?","choices":["Shadow","Tails","Sonic","Knuckles"],"correctIndex":2},
  {"category":"Gaming","difficulty":"Easy","question":"Which game features Creepers?","choices":["Terraria","Minecraft","Roblox","Valheim"],"correctIndex":1},
  {"category":"Gaming","difficulty":"Easy","question":"Which franchise stars Princess Zelda?","choices":["Final Fantasy","Fire Emblem","The Legend of Zelda","Metroid"],"correctIndex":2},
  {"category":"Gaming","difficulty":"Easy","question":"In Fortnite, players jump from a flying what?","choices":["Airship","Jet","Battle Bus","Helicopter"],"correctIndex":2},
  {"category":"Gaming","difficulty":"Easy","question":"Lara Croft is the main character of which series?","choices":["Uncharted","Tomb Raider","Resident Evil","Bayonetta"],"correctIndex":1},
  {"category":"Gaming","difficulty":"Easy","question":"Kratos is the protagonist of which series?","choices":["God of War","Devil May Cry","Darksiders","Castlevania"],"correctIndex":0},
  {"category":"Gaming","difficulty":"Easy","question":"What device do trainers use to catch Pokemon?","choices":["Charm Box","Monster Net","Poke Ball","Capture Cube"],"correctIndex":2},
  {"category":"Gaming","difficulty":"Medium","question":"What is the main setting of Grand Theft Auto V?","choices":["Vice City","Liberty City","Los Santos","San Fierro"],"correctIndex":2},
  {"category":"Gaming","difficulty":"Medium","question":"Which studio developed Elden Ring?","choices":["Capcom","FromSoftware","PlatinumGames","Square Enix"],"correctIndex":1},
  {"category":"Gaming","difficulty":"Medium","question":"What block is used to build a Nether portal in Minecraft?","choices":["Basalt","Obsidian","Blackstone","Deepslate"],"correctIndex":1},
  {"category":"Gaming","difficulty":"Medium","question":"What is Link's horse usually named in The Legend of Zelda?","choices":["Agro","Epona","Roach","Storm"],"correctIndex":1},
  {"category":"Gaming","difficulty":"Medium","question":"Which company publishes the Call of Duty series?","choices":["Ubisoft","Activision","Electronic Arts","Bethesda"],"correctIndex":1},
  {"category":"Gaming","difficulty":"Medium","question":"Teyvat is the world of which game?","choices":["Honkai: Star Rail","Genshin Impact","Tower of Fantasy","Blue Archive"],"correctIndex":1},
  {"category":"Gaming","difficulty":"Medium","question":"Which shell is the classic speed-boosting projectile in Mario Kart?","choices":["Blue Shell","Green Shell","Red Shell","Yellow Shell"],"correctIndex":2},
  {"category":"Gaming","difficulty":"Medium","question":"Which franchise features Vault Hunters and Claptrap?","choices":["Fallout","Borderlands","Ratchet & Clank","Destiny"],"correctIndex":1},
  {"category":"Gaming","difficulty":"Hard","question":"What is Geralt's witcher school called?","choices":["School of the Griffin","School of the Wolf","School of the Bear","School of the Cat"],"correctIndex":1},
  {"category":"Gaming","difficulty":"Hard","question":"Rapture is the underwater city in which game?","choices":["BioShock","Prey","Control","SOMA"],"correctIndex":0},
  {"category":"Gaming","difficulty":"Hard","question":"Who leads the gang in Red Dead Redemption 2?","choices":["Micah Bell","Hosea Matthews","Dutch van der Linde","John Marston"],"correctIndex":2},
  {"category":"Gaming","difficulty":"Hard","question":"What is the best-selling console of all time?","choices":["Nintendo Switch","PlayStation 4","PlayStation 2","Nintendo DS"],"correctIndex":2},
  {"category":"Gaming","difficulty":"Hard","question":"In Resident Evil, what is Umbrella best known as?","choices":["A police task force","A pharmaceutical corporation","A weapons manufacturer","A private military group"],"correctIndex":1},
  {"category":"Gaming","difficulty":"Hard","question":"What is the name of the world in Hollow Knight?","choices":["Hallownest","Lothric","Lordran","Yharnam"],"correctIndex":0},
  {"category":"Gaming","difficulty":"Hard","question":"Which game series is set on the ringworld called Installation 04?","choices":["Mass Effect","Destiny","Halo","Crysis"],"correctIndex":2},
  {"category":"Gaming","difficulty":"Hard","question":"What is the Japanese title of Resident Evil?","choices":["Parasite","Outbreak","Biohazard","Necrozone"],"correctIndex":2},
  {"category":"Gaming","difficulty":"Very Hard","question":"Which 2001 open-world Rockstar game made Liberty City fully 3D?","choices":["Grand Theft Auto 2","Grand Theft Auto III","Grand Theft Auto: Vice City","Driver 2"],"correctIndex":1},
  {"category":"Gaming","difficulty":"Very Hard","question":"What is the name of the kingdom in Demon's Souls?","choices":["Boletaria","Drangleic","Lodran","Yharnam"],"correctIndex":0},
  {"category":"Gaming","difficulty":"Very Hard","question":"What is the original release platform for Persona 4?","choices":["PlayStation 2","PlayStation 3","PS Vita","PSP"],"correctIndex":0},
  {"category":"Gaming","difficulty":"Very Hard","question":"Which Valve game introduced the Gravity Gun?","choices":["Half-Life","Portal","Half-Life 2","Left 4 Dead"],"correctIndex":2},
  {"category":"Gaming","difficulty":"Very Hard","question":"What faction does Kerrigan lead after becoming the Queen of Blades?","choices":["Terran Dominion","Protoss","Zerg","Tal'darim"],"correctIndex":2},
  {"category":"Gaming","difficulty":"Very Hard","question":"Which MMORPG expansion added Northrend?","choices":["The Burning Crusade","Wrath of the Lich King","Cataclysm","Mists of Pandaria"],"correctIndex":1},
  {"category":"Gaming","difficulty":"Very Hard","question":"What was the original release platform for The Last of Us?","choices":["PlayStation 4","PlayStation 3","PlayStation Vita","PlayStation 5"],"correctIndex":1},
  {"category":"Gaming","difficulty":"Very Hard","question":"Which company developed the original Diablo in 1996?","choices":["Blizzard North","id Software","Westwood","BioWare"],"correctIndex":0},
  {"category":"Gaming","difficulty":"Extreme","question":"What was the internal codename for the Nintendo GameCube?","choices":["Dolphin","Revolution","Nitro","Cafe"],"correctIndex":0},
  {"category":"Gaming","difficulty":"Extreme","question":"Which arcade company published the original Pac-Man in Japan?","choices":["Namco","Sega","Taito","Konami"],"correctIndex":0},
  {"category":"Gaming","difficulty":"Extreme","question":"Which game won the first Game of the Year award at The Game Awards in 2014?","choices":["Dragon Age: Inquisition","Dark Souls II","Bayonetta 2","Middle-earth: Shadow of Mordor"],"correctIndex":0},
  {"category":"Gaming","difficulty":"Extreme","question":"What was the first Blizzard game released in 1992?","choices":["Warcraft: Orcs & Humans","The Lost Vikings","Blackthorne","Rock n' Roll Racing"],"correctIndex":1},
  {"category":"Gaming","difficulty":"Extreme","question":"Which company created the Dreamcast?","choices":["SNK","Atari","SEGA","NEC"],"correctIndex":2},
  {"category":"Gaming","difficulty":"Extreme","question":"What is the title of the first Metal Gear game released for MSX2?","choices":["Metal Gear Solid","Metal Gear","Solid Snake","Operation Intrude"],"correctIndex":1},
  {"category":"Gaming","difficulty":"Extreme","question":"Which 1993 shooter popularized deathmatch mode?","choices":["Wolfenstein 3D","Doom","Quake","Duke Nukem 3D"],"correctIndex":1},
  {"category":"Gaming","difficulty":"Extreme","question":"What was the codename of the Nintendo Wii?","choices":["Cafe","Revolution","Nitro","Ultra"],"correctIndex":1},
  {"category":"Anime","difficulty":"Easy","question":"What is Sailor Moon's real first name?","choices":["Rei","Usagi","Minako","Ami"],"correctIndex":1},
  {"category":"Anime","difficulty":"Easy","question":"Who is Edward Elric's younger brother?","choices":["Roy","Alphonse","Winry","Ling"],"correctIndex":1},
  {"category":"Anime","difficulty":"Easy","question":"What item does Light Yagami use in Death Note?","choices":["A sword","A watch","A notebook","A phone"],"correctIndex":2},
  {"category":"Anime","difficulty":"Easy","question":"In Demon Slayer, what is Nezuko to Tanjiro?","choices":["Friend","Cousin","Sister","Mother"],"correctIndex":2},
  {"category":"Anime","difficulty":"Easy","question":"Which pirate crew does Luffy lead?","choices":["Blackbeard Pirates","Heart Pirates","Straw Hat Pirates","Red Hair Pirates"],"correctIndex":2},
  {"category":"Anime","difficulty":"Easy","question":"What is Ash Ketchum's electric partner?","choices":["Raichu","Eevee","Pikachu","Pichu"],"correctIndex":2},
  {"category":"Anime","difficulty":"Easy","question":"What sport is featured in Haikyu!!?","choices":["Basketball","Volleyball","Soccer","Tennis"],"correctIndex":1},
  {"category":"Anime","difficulty":"Easy","question":"What is the name of the titan-killing corps in Attack on Titan?","choices":["Scout Regiment","Royal Guard","Gotei 13","Black Bulls"],"correctIndex":0},
  {"category":"Anime","difficulty":"Medium","question":"What is the name of Naruto's village?","choices":["Sunagakure","Kirigakure","Konohagakure","Iwagakure"],"correctIndex":2},
  {"category":"Anime","difficulty":"Medium","question":"Who teaches Class 1-A in My Hero Academia?","choices":["All Might","Aizawa","Present Mic","Endeavor"],"correctIndex":1},
  {"category":"Anime","difficulty":"Medium","question":"What is Spike Spiegel's profession in Cowboy Bebop?","choices":["Detective","Bounty Hunter","Smuggler","Police Officer"],"correctIndex":1},
  {"category":"Anime","difficulty":"Medium","question":"In One Punch Man, what rank does Saitama start at?","choices":["S-Class","A-Class","B-Class","C-Class"],"correctIndex":3},
  {"category":"Anime","difficulty":"Medium","question":"What magical book system is used in Black Clover?","choices":["Tomes","Spell Books","Grimoires","Codices"],"correctIndex":2},
  {"category":"Anime","difficulty":"Medium","question":"Who is Monkey D. Luffy's grandfather?","choices":["Garp","Shanks","Rayleigh","Dragon"],"correctIndex":0},
  {"category":"Anime","difficulty":"Medium","question":"What is the name of the hidden village where Gaara is from?","choices":["Hidden Mist","Hidden Sand","Hidden Cloud","Hidden Stone"],"correctIndex":1},
  {"category":"Anime","difficulty":"Medium","question":"What organization is Kurapika hunting in Hunter x Hunter?","choices":["Hunter Association","Phantom Troupe","Zoldyck Family","Shadow Beasts"],"correctIndex":1},
  {"category":"Anime","difficulty":"Hard","question":"What is the name of Lelouch's Geass power?","choices":["Absolute Obedience","Future Sight","Time Stop","Memory Rewrite"],"correctIndex":0},
  {"category":"Anime","difficulty":"Hard","question":"Who is the homunculus known as Wrath in FMA: Brotherhood?","choices":["King Bradley","Father","Scar","Selim"],"correctIndex":0},
  {"category":"Anime","difficulty":"Hard","question":"Which studio animated Violet Evergarden?","choices":["MAPPA","Bones","Kyoto Animation","Madhouse"],"correctIndex":2},
  {"category":"Anime","difficulty":"Hard","question":"What is Shinji's EVA unit number?","choices":["Unit-00","Unit-01","Unit-02","Unit-03"],"correctIndex":1},
  {"category":"Anime","difficulty":"Hard","question":"Who is the captain of Squad 13 at the start of Bleach?","choices":["Byakuya Kuchiki","Toshiro Hitsugaya","Jushiro Ukitake","Sajin Komamura"],"correctIndex":2},
  {"category":"Anime","difficulty":"Hard","question":"What is the name of Kira's Stand in JoJo Part 4?","choices":["Gold Experience","Killer Queen","Crazy Diamond","King Crimson"],"correctIndex":1},
  {"category":"Anime","difficulty":"Hard","question":"Who inherits One For All from All Might?","choices":["Bakugo","Todoroki","Izuku Midoriya","Mirio Togata"],"correctIndex":2},
  {"category":"Anime","difficulty":"Hard","question":"What is Griffith's mercenary group called in Berserk?","choices":["Band of the Hawk","Holy Iron Chain","Black Swordsmen","Falcon Guard"],"correctIndex":0},
  {"category":"Anime","difficulty":"Very Hard","question":"Which 1995 film was directed by Mamoru Oshii?","choices":["Akira","Ghost in the Shell","Perfect Blue","Paprika"],"correctIndex":1},
  {"category":"Anime","difficulty":"Very Hard","question":"What is Johan Liebert's origin series?","choices":["Monster","Pluto","Paranoia Agent","Ergo Proxy"],"correctIndex":0},
  {"category":"Anime","difficulty":"Very Hard","question":"Which author created JoJo's Bizarre Adventure?","choices":["Kentaro Miura","Yoshihiro Togashi","Hirohiko Araki","Rumiko Takahashi"],"correctIndex":2},
  {"category":"Anime","difficulty":"Very Hard","question":"What is the final Rebuild of Evangelion film called?","choices":["You Are (Not) Alone","You Can (Not) Redo","Thrice Upon a Time","One More Final"],"correctIndex":2},
  {"category":"Anime","difficulty":"Very Hard","question":"Which manga author created Vagabond?","choices":["Naoki Urasawa","Takehiko Inoue","Makoto Yukimura","Tsugumi Ohba"],"correctIndex":1},
  {"category":"Anime","difficulty":"Very Hard","question":"What is the surname of the siblings in No Game No Life?","choices":["Kujo","Shirogane","Blank","They have no shared surname"],"correctIndex":3},
  {"category":"Anime","difficulty":"Very Hard","question":"Which studio produced Samurai Champloo?","choices":["Bones","Madhouse","Manglobe","MAPPA"],"correctIndex":2},
  {"category":"Anime","difficulty":"Very Hard","question":"Who wrote the manga 20th Century Boys?","choices":["Naoki Urasawa","Inio Asano","Tsugumi Ohba","Katsuhiro Otomo"],"correctIndex":0},
  {"category":"Anime","difficulty":"Extreme","question":"Which studio produced the 2006 anime adaptation of xxxHolic?","choices":["Kyoto Animation","Xebec","Sunrise","Production I.G"],"correctIndex":3},
  {"category":"Anime","difficulty":"Extreme","question":"What false name is Chihiro given in Spirited Away?","choices":["Sen","Haku","Yubaba","Rin"],"correctIndex":0},
  {"category":"Anime","difficulty":"Extreme","question":"Who directed Perfect Blue?","choices":["Masaaki Yuasa","Satoshi Kon","Makoto Shinkai","Mamoru Hosoda"],"correctIndex":1},
  {"category":"Anime","difficulty":"Extreme","question":"What is the name of the artificial city in Ergo Proxy?","choices":["Romdeau","Tokyo-3","NERV City","Lux"],"correctIndex":0},
  {"category":"Anime","difficulty":"Extreme","question":"Which studio animated Ping Pong the Animation?","choices":["Madhouse","Tatsunoko Production","MAPPA","Bones"],"correctIndex":1},
  {"category":"Anime","difficulty":"Extreme","question":"In Serial Experiments Lain, what is the digital network called?","choices":["The Net","The Wired","The Grid","The Link"],"correctIndex":1},
  {"category":"Anime","difficulty":"Extreme","question":"Who is the original author of Monster?","choices":["Hirohiko Araki","Naoki Urasawa","CLAMP","Go Nagai"],"correctIndex":1},
  {"category":"Anime","difficulty":"Extreme","question":"Which 1985 OVA is cited as an early cyberpunk anime classic?","choices":["Megazone 23","Bubblegum Crisis","Akira","Appleseed"],"correctIndex":0},
  {"category":"General Knowledge","difficulty":"Easy","question":"What do bees produce?","choices":["Milk","Honey","Silk","Wax Paper"],"correctIndex":1},
  {"category":"General Knowledge","difficulty":"Easy","question":"Which planet is known as the Red Planet?","choices":["Mars","Jupiter","Saturn","Venus"],"correctIndex":0},
  {"category":"General Knowledge","difficulty":"Easy","question":"How many days are in a leap year?","choices":["364","365","366","367"],"correctIndex":2},
  {"category":"General Knowledge","difficulty":"Easy","question":"What gas do plants absorb from the air?","choices":["Oxygen","Nitrogen","Carbon Dioxide","Helium"],"correctIndex":2},
  {"category":"General Knowledge","difficulty":"Easy","question":"Which ocean lies between Africa and Australia?","choices":["Atlantic Ocean","Indian Ocean","Pacific Ocean","Arctic Ocean"],"correctIndex":1},
  {"category":"General Knowledge","difficulty":"Easy","question":"How many sides does a hexagon have?","choices":["5","6","7","8"],"correctIndex":1},
  {"category":"General Knowledge","difficulty":"Easy","question":"Which part of the body do you use to smell?","choices":["Ear","Nose","Tongue","Eye"],"correctIndex":1},
  {"category":"General Knowledge","difficulty":"Easy","question":"What is the freezing point of water in Celsius?","choices":["0","10","32","100"],"correctIndex":0},
  {"category":"General Knowledge","difficulty":"Medium","question":"What is the largest desert on Earth?","choices":["Sahara","Gobi","Antarctic Desert","Arabian Desert"],"correctIndex":2},
  {"category":"General Knowledge","difficulty":"Medium","question":"Which language has the most native speakers worldwide?","choices":["English","Hindi","Mandarin Chinese","Spanish"],"correctIndex":2},
  {"category":"General Knowledge","difficulty":"Medium","question":"What is the tallest mountain above sea level?","choices":["K2","Kangchenjunga","Mount Everest","Lhotse"],"correctIndex":2},
  {"category":"General Knowledge","difficulty":"Medium","question":"What does DNA stand for?","choices":["Dynamic Nuclear Acid","Deoxyribonucleic Acid","Dual Nitrogen Array","Deoxyribose Nucleic Atom"],"correctIndex":1},
  {"category":"General Knowledge","difficulty":"Medium","question":"Which country is home to the city of Kyoto?","choices":["China","South Korea","Japan","Thailand"],"correctIndex":2},
  {"category":"General Knowledge","difficulty":"Medium","question":"Which organ pumps blood through the human body?","choices":["Lung","Liver","Heart","Kidney"],"correctIndex":2},
  {"category":"General Knowledge","difficulty":"Medium","question":"What is the main ingredient in guacamole?","choices":["Cucumber","Avocado","Spinach","Zucchini"],"correctIndex":1},
  {"category":"General Knowledge","difficulty":"Medium","question":"Which metal is liquid at room temperature?","choices":["Mercury","Silver","Lead","Tin"],"correctIndex":0},
  {"category":"General Knowledge","difficulty":"Hard","question":"Which scientist proposed the three laws of motion?","choices":["Newton","Einstein","Galileo","Tesla"],"correctIndex":0},
  {"category":"General Knowledge","difficulty":"Hard","question":"What is the longest river in South America?","choices":["Parana","Orinoco","Amazon","Madeira"],"correctIndex":2},
  {"category":"General Knowledge","difficulty":"Hard","question":"Which country gifted the Statue of Liberty to the United States?","choices":["France","Spain","Italy","United Kingdom"],"correctIndex":0},
  {"category":"General Knowledge","difficulty":"Hard","question":"What is the smallest prime number?","choices":["0","1","2","3"],"correctIndex":2},
  {"category":"General Knowledge","difficulty":"Hard","question":"Which layer of Earth lies directly below the crust?","choices":["Outer Core","Mantle","Inner Core","Lithosphere"],"correctIndex":1},
  {"category":"General Knowledge","difficulty":"Hard","question":"What is the currency of Switzerland?","choices":["Euro","Franc","Krone","Lira"],"correctIndex":1},
  {"category":"General Knowledge","difficulty":"Hard","question":"Which planet rotates on its side?","choices":["Mars","Saturn","Uranus","Mercury"],"correctIndex":2},
  {"category":"General Knowledge","difficulty":"Hard","question":"What is the largest internal organ in the human body?","choices":["Heart","Liver","Lung","Brain"],"correctIndex":1},
  {"category":"General Knowledge","difficulty":"Very Hard","question":"What is the SI unit of electric resistance?","choices":["Volt","Ohm","Ampere","Watt"],"correctIndex":1},
  {"category":"General Knowledge","difficulty":"Very Hard","question":"Which empire built Machu Picchu?","choices":["Aztec","Maya","Inca","Olmec"],"correctIndex":2},
  {"category":"General Knowledge","difficulty":"Very Hard","question":"What is the deepest ocean trench on Earth?","choices":["Peru-Chile Trench","Java Trench","Mariana Trench","Puerto Rico Trench"],"correctIndex":2},
  {"category":"General Knowledge","difficulty":"Very Hard","question":"Which scientist discovered penicillin?","choices":["Louis Pasteur","Alexander Fleming","Robert Koch","Jonas Salk"],"correctIndex":1},
  {"category":"General Knowledge","difficulty":"Very Hard","question":"What is the capital of Kazakhstan?","choices":["Almaty","Tashkent","Astana","Bishkek"],"correctIndex":2},
  {"category":"General Knowledge","difficulty":"Very Hard","question":"Which philosopher wrote The Republic?","choices":["Aristotle","Socrates","Plato","Descartes"],"correctIndex":2},
  {"category":"General Knowledge","difficulty":"Very Hard","question":"What is the most abundant gas in Earth's atmosphere?","choices":["Oxygen","Carbon Dioxide","Nitrogen","Argon"],"correctIndex":2},
  {"category":"General Knowledge","difficulty":"Very Hard","question":"Which country has the largest population in Africa?","choices":["Nigeria","Egypt","Ethiopia","South Africa"],"correctIndex":0},
  {"category":"General Knowledge","difficulty":"Extreme","question":"What is the only letter not appearing in any U.S. state name?","choices":["Q","X","Z","J"],"correctIndex":0},
  {"category":"General Knowledge","difficulty":"Extreme","question":"Which treaty ended the Thirty Years' War in 1648?","choices":["Treaty of Versailles","Peace of Westphalia","Treaty of Utrecht","Congress of Vienna"],"correctIndex":1},
  {"category":"General Knowledge","difficulty":"Extreme","question":"What is the study of fungi called?","choices":["Bryology","Mycology","Entomology","Ornithology"],"correctIndex":1},
  {"category":"General Knowledge","difficulty":"Extreme","question":"Which star is closest to Earth after the Sun?","choices":["Barnard's Star","Proxima Centauri","Sirius","Alpha Centauri A"],"correctIndex":1},
  {"category":"General Knowledge","difficulty":"Extreme","question":"What is the capital city of Slovenia?","choices":["Bratislava","Zagreb","Ljubljana","Skopje"],"correctIndex":2},
  {"category":"General Knowledge","difficulty":"Extreme","question":"In Roman numerals, what number is represented by XL?","choices":["30","40","50","60"],"correctIndex":1},
  {"category":"General Knowledge","difficulty":"Extreme","question":"Which element's chemical symbol is W?","choices":["Tungsten","Tin","Titanium","Tantalum"],"correctIndex":0},
  {"category":"General Knowledge","difficulty":"Extreme","question":"How many valves does the human heart have?","choices":["2","3","4","5"],"correctIndex":2},
  {"category":"Movies & Series","difficulty":"Easy","question":"Who is Harry Potter's best red-haired friend?","choices":["Neville Longbottom","Draco Malfoy","Ron Weasley","Cedric Diggory"],"correctIndex":2},
  {"category":"Movies & Series","difficulty":"Easy","question":"What color is the Hulk?","choices":["Red","Blue","Green","Gray"],"correctIndex":2},
  {"category":"Movies & Series","difficulty":"Easy","question":"Which animated film features the song Let It Go?","choices":["Moana","Tangled","Frozen","Encanto"],"correctIndex":2},
  {"category":"Movies & Series","difficulty":"Easy","question":"What is the name of Baby Yoda in The Mandalorian?","choices":["Grogu","Yaddle","Ezra","Pabu"],"correctIndex":0},
  {"category":"Movies & Series","difficulty":"Easy","question":"Which superhero uses a vibranium shield?","choices":["Iron Man","Captain America","Thor","Black Panther"],"correctIndex":1},
  {"category":"Movies & Series","difficulty":"Easy","question":"What is the name of the clownfish in Finding Nemo?","choices":["Marlin","Dory","Nemo","Gill"],"correctIndex":2},
  {"category":"Movies & Series","difficulty":"Easy","question":"Which series follows kids in Hawkins?","choices":["Dark","Stranger Things","Wednesday","The OA"],"correctIndex":1},
  {"category":"Movies & Series","difficulty":"Easy","question":"Who lives in a pineapple under the sea?","choices":["Patrick Star","Squidward","SpongeBob SquarePants","Mr. Krabs"],"correctIndex":2},
  {"category":"Movies & Series","difficulty":"Medium","question":"Who directed Jurassic Park?","choices":["James Cameron","Steven Spielberg","Ridley Scott","Peter Jackson"],"correctIndex":1},
  {"category":"Movies & Series","difficulty":"Medium","question":"What is the name of the coffee shop in Friends?","choices":["Central Brew","Central Perk","Monica's Cafe","Perk Place"],"correctIndex":1},
  {"category":"Movies & Series","difficulty":"Medium","question":"Which actor played Jack Sparrow?","choices":["Orlando Bloom","Johnny Depp","Geoffrey Rush","Javier Bardem"],"correctIndex":1},
  {"category":"Movies & Series","difficulty":"Medium","question":"Which series features the Shelby family?","choices":["Vikings","Peaky Blinders","Boardwalk Empire","Sons of Anarchy"],"correctIndex":1},
  {"category":"Movies & Series","difficulty":"Medium","question":"What is the name of the hotel in The Shining?","choices":["Bates Motel","Overlook Hotel","Grand Northern","Hotel Cortez"],"correctIndex":1},
  {"category":"Movies & Series","difficulty":"Medium","question":"Who plays Eleven in Stranger Things?","choices":["Sadie Sink","Millie Bobby Brown","Natalia Dyer","Maya Hawke"],"correctIndex":1},
  {"category":"Movies & Series","difficulty":"Medium","question":"Which MCU film introduced Black Panther?","choices":["Avengers: Age of Ultron","Black Panther","Captain America: Civil War","Iron Man 3"],"correctIndex":2},
  {"category":"Movies & Series","difficulty":"Medium","question":"What is the fictional substance mined on Pandora in Avatar?","choices":["Adamantium","Unobtanium","Vibranium","Promethium"],"correctIndex":1},
  {"category":"Movies & Series","difficulty":"Hard","question":"What is the real name of the Bride in Kill Bill?","choices":["Elle Driver","Beatrix Kiddo","O-Ren Ishii","Vernita Green"],"correctIndex":1},
  {"category":"Movies & Series","difficulty":"Hard","question":"Which actor played the Joker in The Dark Knight?","choices":["Joaquin Phoenix","Jared Leto","Heath Ledger","Jack Nicholson"],"correctIndex":2},
  {"category":"Movies & Series","difficulty":"Hard","question":"What is the name of the island in Jurassic Park?","choices":["Isla Nublar","Isla Sorna","Skull Island","Muir Island"],"correctIndex":0},
  {"category":"Movies & Series","difficulty":"Hard","question":"Who composed the music for Interstellar?","choices":["John Williams","Hans Zimmer","Ludwig Goransson","James Newton Howard"],"correctIndex":1},
  {"category":"Movies & Series","difficulty":"Hard","question":"What is Walter White's alter ego?","choices":["Saul Goodman","Heisenberg","Cap'n Cook","Tighten"],"correctIndex":1},
  {"category":"Movies & Series","difficulty":"Hard","question":"Which 1982 film features Roy Batty?","choices":["Alien","Blade Runner","Tron","The Thing"],"correctIndex":1},
  {"category":"Movies & Series","difficulty":"Hard","question":"What is the title of the first Lord of the Rings film?","choices":["The Two Towers","The Return of the King","The Fellowship of the Ring","The Hobbit"],"correctIndex":2},
  {"category":"Movies & Series","difficulty":"Hard","question":"Who directed The Truman Show?","choices":["Peter Weir","Robert Zemeckis","David Fincher","Ron Howard"],"correctIndex":0},
  {"category":"Movies & Series","difficulty":"Very Hard","question":"Which actor starred as Travis Bickle in Taxi Driver?","choices":["Al Pacino","Jack Nicholson","Robert De Niro","Dustin Hoffman"],"correctIndex":2},
  {"category":"Movies & Series","difficulty":"Very Hard","question":"What is the name of the ship in Alien?","choices":["Sulaco","Serenity","Nostromo","Bebop"],"correctIndex":2},
  {"category":"Movies & Series","difficulty":"Very Hard","question":"Which director made Pan's Labyrinth?","choices":["Alfonso Cuaron","Guillermo del Toro","Alejandro Inarritu","Pedro Almodovar"],"correctIndex":1},
  {"category":"Movies & Series","difficulty":"Very Hard","question":"Which film won Best Picture for 2020?","choices":["1917","Joker","Parasite","Ford v Ferrari"],"correctIndex":2},
  {"category":"Movies & Series","difficulty":"Very Hard","question":"What is the name of Tony Soprano's psychiatrist?","choices":["Dr. Melfi","Dr. Chase","Dr. Wilson","Dr. Cuddy"],"correctIndex":0},
  {"category":"Movies & Series","difficulty":"Very Hard","question":"Who directed The Grand Budapest Hotel?","choices":["Wes Anderson","Noah Baumbach","David Fincher","Taika Waititi"],"correctIndex":0},
  {"category":"Movies & Series","difficulty":"Very Hard","question":"Who played Anton Chigurh in No Country for Old Men?","choices":["Javier Bardem","Josh Brolin","Tommy Lee Jones","Benicio del Toro"],"correctIndex":0},
  {"category":"Movies & Series","difficulty":"Very Hard","question":"Which studio released Spirited Away in the U.S. through Disney?","choices":["Miramax","Touchstone","Walt Disney Pictures","Pixar"],"correctIndex":2},
  {"category":"Movies & Series","difficulty":"Extreme","question":"Which silent-era director made Metropolis?","choices":["F.W. Murnau","Fritz Lang","Sergei Eisenstein","Carl Dreyer"],"correctIndex":1},
  {"category":"Movies & Series","difficulty":"Extreme","question":"What is the name of the apartment building in Rosemary's Baby?","choices":["The Dakota","The Bramford","The Overlook","The Chelsea"],"correctIndex":1},
  {"category":"Movies & Series","difficulty":"Extreme","question":"Who played Lawrence of Arabia in the 1962 film?","choices":["Peter O'Toole","Alec Guinness","Richard Burton","Omar Sharif"],"correctIndex":0},
  {"category":"Movies & Series","difficulty":"Extreme","question":"What was Disney's first feature-length animated film?","choices":["Pinocchio","Snow White and the Seven Dwarfs","Fantasia","Bambi"],"correctIndex":1},
  {"category":"Movies & Series","difficulty":"Extreme","question":"Which filmmaker directed Stalker (1979)?","choices":["Andrei Tarkovsky","Ingmar Bergman","Akira Kurosawa","Krzysztof Kieslowski"],"correctIndex":0},
  {"category":"Movies & Series","difficulty":"Extreme","question":"Which actress stars in Mulholland Drive as Betty Elms?","choices":["Laura Harring","Naomi Watts","Julianne Moore","Nicole Kidman"],"correctIndex":1},
  {"category":"Movies & Series","difficulty":"Extreme","question":"Who directed Seven Samurai?","choices":["Yasujiro Ozu","Akira Kurosawa","Masaki Kobayashi","Kenji Mizoguchi"],"correctIndex":1},
  {"category":"Movies & Series","difficulty":"Extreme","question":"Which film is Orson Welles' masterpiece about Charles Foster Kane?","choices":["Touch of Evil","The Third Man","Citizen Kane","The Magnificent Ambersons"],"correctIndex":2},
  {"category":"Music","difficulty":"Easy","question":"Which singer is known for the album 21?","choices":["Adele","Taylor Swift","Dua Lipa","Beyonce"],"correctIndex":0},
  {"category":"Music","difficulty":"Easy","question":"How many strings does a standard guitar have?","choices":["4","5","6","7"],"correctIndex":2},
  {"category":"Music","difficulty":"Easy","question":"Which instrument has black and white keys?","choices":["Violin","Trumpet","Piano","Drum"],"correctIndex":2},
  {"category":"Music","difficulty":"Easy","question":"Which pop star released the song Shake It Off?","choices":["Ariana Grande","Taylor Swift","Katy Perry","Olivia Rodrigo"],"correctIndex":1},
  {"category":"Music","difficulty":"Easy","question":"Which group sang Dancing Queen?","choices":["ABBA","Bee Gees","Boney M.","A-ha"],"correctIndex":0},
  {"category":"Music","difficulty":"Easy","question":"What do you call a person who writes songs?","choices":["Producer","Conductor","Songwriter","Promoter"],"correctIndex":2},
  {"category":"Music","difficulty":"Easy","question":"Which instrument is played with drumsticks?","choices":["Cello","Flute","Drums","Harp"],"correctIndex":2},
  {"category":"Music","difficulty":"Easy","question":"Which singer is known as the King of Pop?","choices":["Elvis Presley","Michael Jackson","Prince","Bruno Mars"],"correctIndex":1},
  {"category":"Music","difficulty":"Medium","question":"Which band released Bohemian Rhapsody?","choices":["Queen","The Beatles","The Rolling Stones","ELO"],"correctIndex":0},
  {"category":"Music","difficulty":"Medium","question":"Which symbol raises a note by one semitone?","choices":["Flat","Sharp","Natural","Rest"],"correctIndex":1},
  {"category":"Music","difficulty":"Medium","question":"Which artist released the album Future Nostalgia?","choices":["Rihanna","Dua Lipa","Sia","Lorde"],"correctIndex":1},
  {"category":"Music","difficulty":"Medium","question":"How many members were in the classic Beatles lineup?","choices":["3","4","5","6"],"correctIndex":1},
  {"category":"Music","difficulty":"Medium","question":"Which instrument is Yo-Yo Ma famous for playing?","choices":["Piano","Cello","Clarinet","Viola"],"correctIndex":1},
  {"category":"Music","difficulty":"Medium","question":"What is the highest common female singing voice type?","choices":["Alto","Mezzo-soprano","Soprano","Contralto"],"correctIndex":2},
  {"category":"Music","difficulty":"Medium","question":"Which rapper released the album To Pimp a Butterfly?","choices":["J. Cole","Drake","Kendrick Lamar","Tyler, the Creator"],"correctIndex":2},
  {"category":"Music","difficulty":"Medium","question":"Which band is fronted by Chris Martin?","choices":["Coldplay","Muse","Maroon 5","Imagine Dragons"],"correctIndex":0},
  {"category":"Music","difficulty":"Hard","question":"Which composer wrote The Four Seasons?","choices":["Vivaldi","Mozart","Bach","Tchaikovsky"],"correctIndex":0},
  {"category":"Music","difficulty":"Hard","question":"Which singer's real name is Stefani Germanotta?","choices":["Lady Gaga","P!nk","Kesha","Sia"],"correctIndex":0},
  {"category":"Music","difficulty":"Hard","question":"What term means gradually getting louder in music?","choices":["Diminuendo","Staccato","Crescendo","Legato"],"correctIndex":2},
  {"category":"Music","difficulty":"Hard","question":"Which band recorded the album Dark Side of the Moon?","choices":["Led Zeppelin","Pink Floyd","Genesis","Rush"],"correctIndex":1},
  {"category":"Music","difficulty":"Hard","question":"Who composed Clair de Lune?","choices":["Debussy","Chopin","Ravel","Satie"],"correctIndex":0},
  {"category":"Music","difficulty":"Hard","question":"Which Nirvana album features Smells Like Teen Spirit?","choices":["Bleach","Nevermind","In Utero","Incesticide"],"correctIndex":1},
  {"category":"Music","difficulty":"Hard","question":"Which producer tag is associated with Metro Boomin?","choices":["Mustard on the beat","If Young Metro don't trust you","We got London on da Track","Take a Daytrip"],"correctIndex":1},
  {"category":"Music","difficulty":"Hard","question":"What is the relative minor of C major?","choices":["A minor","E minor","D minor","G minor"],"correctIndex":0},
  {"category":"Music","difficulty":"Very Hard","question":"Which composer became deaf later in life but continued to write major works?","choices":["Beethoven","Haydn","Berlioz","Liszt"],"correctIndex":0},
  {"category":"Music","difficulty":"Very Hard","question":"Which jazz trumpeter released the album Kind of Blue?","choices":["Chet Baker","Louis Armstrong","Miles Davis","Dizzy Gillespie"],"correctIndex":2},
  {"category":"Music","difficulty":"Very Hard","question":"What does BPM stand for in music production?","choices":["Beats Per Measure","Beats Per Minute","Bars Per Melody","Balance Per Mix"],"correctIndex":1},
  {"category":"Music","difficulty":"Very Hard","question":"Which singer released the 2020 album folklore?","choices":["Phoebe Bridgers","Taylor Swift","Lana Del Rey","Billie Eilish"],"correctIndex":1},
  {"category":"Music","difficulty":"Very Hard","question":"Which mode uses the same notes as C major but starts on D?","choices":["Dorian","Mixolydian","Lydian","Phrygian"],"correctIndex":0},
  {"category":"Music","difficulty":"Very Hard","question":"Which band made the concept album American Idiot?","choices":["Blink-182","Green Day","The Offspring","Sum 41"],"correctIndex":1},
  {"category":"Music","difficulty":"Very Hard","question":"Which opera did Mozart compose that features the Queen of the Night?","choices":["Don Giovanni","The Magic Flute","The Marriage of Figaro","Così fan tutte"],"correctIndex":1},
  {"category":"Music","difficulty":"Very Hard","question":"Which artist released Channel Orange before Blonde?","choices":["The Weeknd","Frank Ocean","Tyler, the Creator","Miguel"],"correctIndex":1},
  {"category":"Music","difficulty":"Extreme","question":"Which Russian composer wrote The Rite of Spring?","choices":["Prokofiev","Stravinsky","Shostakovich","Rimsky-Korsakov"],"correctIndex":1},
  {"category":"Music","difficulty":"Extreme","question":"What is the term for a composition for one solo instrument?","choices":["Duet","Solo","Etude","Sonata"],"correctIndex":2},
  {"category":"Music","difficulty":"Extreme","question":"Which jazz musician was nicknamed Bird?","choices":["Charlie Parker","John Coltrane","Thelonious Monk","Charles Mingus"],"correctIndex":0},
  {"category":"Music","difficulty":"Extreme","question":"Which Bjork album begins with the track Hidden Place?","choices":["Vespertine","Post","Homogenic","Debut"],"correctIndex":0},
  {"category":"Music","difficulty":"Extreme","question":"In orchestral terms, what does pizzicato instruct string players to do?","choices":["Play softly","Pluck the strings","Use double speed","Switch to harmonics"],"correctIndex":1},
  {"category":"Music","difficulty":"Extreme","question":"Which artist released the album Dummy in 1994?","choices":["Massive Attack","Portishead","Tricky","Morcheeba"],"correctIndex":1},
  {"category":"Music","difficulty":"Extreme","question":"Which microtonal instrument features a ribbon controller and was invented in the 1920s?","choices":["Theremin","Ondes Martenot","Mellotron","Clavinet"],"correctIndex":1},
  {"category":"Music","difficulty":"Extreme","question":"Which composer wrote the opera Wozzeck?","choices":["Mahler","Berg","Schoenberg","Webern"],"correctIndex":1}
];
